## --------------- Sample APIs ----------------------------------

### Create a sample

POST http://localhost:8080/samples/create
Content-Type: application/json

{
    "sampleType" : "Urine",
    "parameterList" : "Steroids",
    "batchDesc" : "This is an example testing sample desc for another sample"
}

### Get a sample based on the Sample ID

GET http://13.200.233.118:8080/samples/getsample/1

### List all the samples available

GET http://sampletracking-alb-1324203417.ap-south-1.elb.amazonaws.com/samples/listsamples

### Search for a sample by their column and a value.

GET http://localhost:8080/samples/search?columnToSearch=sampleTy&searchValue=Piss

### Update the status of a sample

PATCH http://localhost:8080/samples/updatestatus/1?updatedStatus=archived

### Enter or Update a value of a sample

PATCH http://localhost:8080/samples/updatevalue/1?parameterList=Cholesterol&value=23.44

### Delete a sample

DELETE http://localhost:8080/samples/deletesample/1

## ----------------------- Batch APIs ------------------------------------

### Create a Batch

POST  http://localhost:8080/batch/createBatch
Content-Type: application/json

{
  "noOfSample": 3,
  "batchDesc": "This is a new Batch with 3 samples",
  "sampleParameterList": "Glucose",
  "sampleType": "Blood"
}

### List all the Batches

GET http://localhost:8080/batch/listBatches

### Get a batch

GET http://localhost:8080/batch/getBatch/1

### Delete a Batch

DELETE http://localhost:8080/batch/deleteBatch/1?forceDelete=false