server:
  port: 8080

spring:
  application:
    name: sample-tracking-api

  datasource:
   # only for local modification
    url: ${DB_URL:jdbc:mysql://localhost:3306/sampletracking}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
